# Generated by Django 3.2.5 on 2021-07-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_searchedwords'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchedWords',
            new_name='SearchedWord',
        ),
    ]
