# Generated by Django 3.2.5 on 2021-08-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_profile_savedmovies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='savedMovies',
            field=models.JSONField(null=True),
        ),
    ]
