# Generated by Django 3.2.5 on 2021-08-09 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_profile_savedmovies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='savedMovies',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
